services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - /home/jgasparo/data/mariadb:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception
    secrets:
      - db_root_password
      - db_password

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    volumes:
      - /home/jgasparo/data/wordpress:/home/jgasparo/data/www/wordpress
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WP_DB_HOST}
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      WORDPRESS_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WORDPRESS_TITLE: ${WP_TITLE}
      WORDPRESS_DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_USER_NAME: ${WP_USER_NAME}
      WORDPRESS_USER_EMAIL: ${WP_USER_EMAIL}     
    volumes:
      - /home/jgasparo/data/wordpress:/home/jgasparo/data/www/wordpress
    expose:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - inception
    secrets:
      - credentials
      - db_password
      - wp_admin_password
      - wp_user_password


networks:
  inception:
    driver: bridge

secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
