services:

  mariadb:
    build: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PWD}
    volumes:
      - db_data:/var/lib/mysql
      - ./requirements/mariadb/tools/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "3306"

  wordpress:
    build: ./requirements/wordpress
    environment:
      WORDPRESS_DB_HOST: ${WP_DB_HOST}
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PWD}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      WORDPRESS_ADMIN_USER: ${WP_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WP_ADMIN_PWD}
      WORDPRESS_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WORDPRESS_TITLE: ${WP_TITLE}
      WORDPRESS_DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - wp_data:/home/jgasparo/data/www/wordpress
    expose:
      - "9000"
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    volumes:
      - wp_data:/home/jgasparo/data/www/wordpress
    ports:
      - "443:443"
    depends_on:
      - wordpress

volumes:
  db_data:
  wp_data: