services:

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/home/jgasparo/data/www/wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    image: nginx
    volumes:
      - wp_data:/home/jgasparo/data/www/wordpress
    ports:
      - "443:443"
    depends_on:
      - wordpress

volumes:
  db_data:
  wp_data: